provider: postgresql
major-version: 3
docker: true
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
integrationTestProvider: true
esc:
  enabled: true
  environment: imports/github-secrets # No repo-specific secrets.
