// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface ProviderClientcert {
    cert?: string;
    key?: string;
}

export interface SchemaPolicy {
    /**
     * Should the specified ROLE have CREATE privileges to the specified SCHEMA.
     */
    create?: boolean;
    /**
     * Should the specified ROLE have CREATE privileges to the specified SCHEMA and the ability to GRANT the CREATE privilege to other ROLEs.
     */
    createWithGrant?: boolean;
    /**
     * The ROLE who is receiving the policy.  If this value is empty or not specified it implies the policy is referring to the [`PUBLIC` role](https://www.postgresql.org/docs/current/static/sql-grant.html).
     */
    role?: string;
    /**
     * Should the specified ROLE have USAGE privileges to the specified SCHEMA.
     */
    usage?: boolean;
    /**
     * Should the specified ROLE have USAGE privileges to the specified SCHEMA and the ability to GRANT the USAGE privilege to other ROLEs.
     */
    usageWithGrant?: boolean;
}
export namespace config {
    export interface Clientcert {
        cert: string;
        key: string;
    }
}
