// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PostgreSql.Inputs
{

    public sealed class ProviderClientcertArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The SSL client certificate file path. The file must contain PEM encoded data.
        /// </summary>
        [Input("cert", required: true)]
        public Input<string> Cert { get; set; } = null!;

        /// <summary>
        /// The SSL client certificate private key file path. The file must contain PEM encoded data.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// Must be set to true if you are inlining the cert/key instead of using a file path.
        /// </summary>
        [Input("sslinline")]
        public Input<bool>? Sslinline { get; set; }

        public ProviderClientcertArgs()
        {
        }
        public static new ProviderClientcertArgs Empty => new ProviderClientcertArgs();
    }
}
